### ISSUE TITLE
about outerproduct

### ISSUE THREAD

**Issue by janboeye** [xuqiantong/CUDA-Winograd#1]
hi, @xuqiantong 

How can innerproduct be converted to outer product?

Thanks
Yuanbo

**Comment by Grekery** [comment]
Do you know this program is only for the single size in it, or for many different size, thanks!

**Comment by xuqiantong** [comment]
@janboeye I did not quite understand about your question. My implementation is using the idea of outer-product on small chunks of output. If you have any specific concern about the implementation here, please create a new issue. closing.

**Comment by xuqiantong** [comment]
@Grekery Each kernel I implemented is for a specific input/output size as well as the kernels.
