### ISSUE TITLE
Trying to fix the bug in Kernel128_one.cu.

### ISSUE THREAD

**Issue by oscarriddle** [xuqiantong/CUDA-Winograd#2]
```
 65   float *input = get_parameter(inputName128one, 14*14*512);
 66   float *weight = get_parameter(weightName128one, 128*512);

 99   cudaMemcpy(input_, input, nInput<<2, cudaMemcpyHostToDevice);
100   cudaMemcpy(weight_, weight_, nWeights<<2, cudaMemcpyHostToDevice);
101   cudaMemcpy(bnBias_, bnBias_myKernel, 128<<2, cudaMemcpyHostToDevice);
102   cudaMemcpy(bnScale_, bnScale_myKernel, 128<<2, cudaMemcpyHostToDevice);
```
Generated weight data is loaded at line 66 with ptr name weight, but at line 100, you assign an initialized position to device pointer weight_, which will be all zero.

cudnn part also uses weight_ to compute, so I changed line 100 to:
`100   cudaMemcpy(weight_, weight, nWeights<<2, cudaMemcpyHostToDevice);`
Then I got this result:
```
---- Iter: 9 ----
TotalTime = 58 us
cudaSuccess
cuDNN TotalTime = 113 us
cudaSuccess
[max_error: 65141.292969][error_cnt: 18947]
Average Total Time: [Mine: 59 us], [cuDNN: 111 us]
```
Seems your kernel is not doing the correct calculation.

Please help address the issue, thanks.

**Comment by xuqiantong** [comment]
@oscarriddle Nice catch! Seems like this bug appears in all my 1 x 1 kernel tests. It will be great if you can help me to find the issue and send out a PR. I may also try to fix it later when I have some bandwidth. Thanks!

**Comment by oscarriddle** [comment]
Hi @xuqiantong , Thanks for your reply. 
I fixed the pointer assignment, but got a wrong result as stated above. 
So I'm trying to read the calculation kernel but a little bit confused about the logic:
```
 45   for (int k = 0; k < 128; k += 16) {
 46     for (int i = 0; i < 16; i++) {
 47       weights[ind + i*512] = B[(k+i)*512 + ind]; 
 48       }
 49     __syncthreads();
 50     float *A_start = input + k*64; 
 51     for (int p = 0; p < 64; p++) {
 52       output[ind] += A_start[line*512 + p] * weights[in_channel + p*128];
 53     }
 54     __syncthreads();
 55   }
```
According to my understanding, line 45,46,47 is to rearrange the weight data. The original weight matrix has 128\*512 elements (rows\*column). Before the barrier at line 49, every (16, 512) partitioned weight data are allocated orderly into the 1D array named "weights". 

Then I'm not quite clear the operation at line 51,52, it seems to do the outer-product but whether there are some good intuitions to understand the iterator p and *A_start?

**Comment by xuqiantong** [comment]
Here, we are doing outer-product using part of weights (with size 128 x 64) and part of input. `A_start` should be the beginning position of that part of input and we are summing over 64 elements into a certain output pixel `output[ind]`.

**Comment by oscarriddle** [comment]
Hi @xuqiantong ,
Till the line `49     __syncthreads();`, the matrix input has shape (4 rows*512 cols), and weights has shape (16 * 512), then line `50     float *A_start = input + k*64;` defines the start point is every 2048 elements of input, which implies every thread handles 4 elements.

In my intuition, each thread handles 4 elements from the input matrix in column direction, which should multiplies with 4 elements from the weights matrix in column direction (due to the weight matrix isn't transposed) to compute the outer-product. However, this is not matching with the shape of the weithg matrix (16 * 512), and seems misunderstood your idea. 

Could you provide more intuitive explanations? That will be much appreciated.

**Comment by xuqiantong** [comment]
I think it's 64 * 128 instead of 16 * 512. Same size though. Make it 512/16 is to better utilize the threads. 
```
float *weights = shared_ + 512*4, *output = weights + 128*64, *input = shared_;
```
This line defines the size of each buffer in the shared memory.

**Comment by oscarriddle** [comment]
@xuqiantong 
The in and out methods of 128 1x1 kernels are getting wrong results.
Seems the calculation part is incorrect, I tried to rewrite the calculation but still not get it.
Would you help rewrite the calculation part in 1x1 kernels? Your understanding of the context should be much better.

Log of function  kernel_128_1_in()
```
TotalTime = 64 us
cudaSuccess
cuDNN TotalTime = 111 us
cudaSuccess
0.000000 and 0.000000 
[max_error: 65141.292969][error_cnt: 18947]
```
Log of the function  kernel_128_1_out()
```
cudaSuccess
cuDNN TotalTime = 113 us
cudaSuccess
-138.059067 and 58.676163 
[max_error: 68952.289062][error_cnt: 100352]
```

**Comment by xuqiantong** [comment]
Hi @oscarriddle, sorry I don't have bandwidth to look into this recently. But I will do fix it later. It will be great if you can help me to debug this for now. Thanks!

**Comment by oscarriddle** [comment]
Hi @xuqiantong . Yes, I'm trying to make a deep understanding of your project. It's indeed a nice job.

In the output_checker function
```
float output_checker(float *A, float *B, int len, int channel, int shift) {
        int error_cnt = 0;
        float max_error = 0;
        for (int i = 0; i < len; i++) {
                for (int j = 0; j < len; j++) {
                        for (int k = 0; k < channel; k++) {
                                float diff = fabs(A[((i+shift)*(len+2*shift)+j+shift)*channel + k] - B[(i*len+j)*channel + k]);
                                if (diff > 1e-5) error_cnt++;
                                if (diff > max_error) max_error = diff;
                        }
                }
        }
  printf("%0f and %0f \n", A[1], B[1]);
        printf("[max_error: %f][error_cnt: %d]\n", max_error, error_cnt);
}

```
You added a shift to the height and width of each channel, which is actually the padded element.
I noticed you added the a tensor descriptor with (14,14,128) in cuDNN method as below:
```
        status = cudnnSetTensor4dDescriptor(ydesc, CUDNN_TENSOR_NHWC, CUDNN_DATA_FLOAT, 1, 128, 14, 14);
        if (status != CUDNN_STATUS_SUCCESS) printf("failed5\n");
```
```
      status = cudnnConvolutionForward(handle, &one,
                xdesc, input, wdesc, l_weights,
                conv_desc, algo,
                extra, size, &zero,
                ydesc, output);
        if (status != CUDNN_STATUS_SUCCESS) printf("Not Successed1\n");

```
In the real circumstances, I guess the output tensor after ATIA function shall be (14,14,128).


Thanks

**Comment by oscarriddle** [comment]
Hi @xuqiantong 

I have another question about your MM transformation.
In the report, you mentioned: 

> As shown in Figure 2, we notice that we are computing the convolution of a grid of input against the same part of kernels. For example, the left-top corner of each input kernel (B11) will only interact with the left-top corner (A11) of each 6x6 tile of the input tensor and similar pattern can apply to elements in other positions (Aij and Bij ). This way, we can form 36 distinct matrix multiplication for this convolution computing (n2 data with n3 computation).

Why B11 will only interact with A11?

After GTkG, the kernel is transformed from (3*3*C) to (6*6*C). 
Originally speaking, each kernel needs to multiple with a (6*6*C) transformed tile (A), which is transformed from a (6*6*C) original tile by BTdB with 2 overlapping. Then generates a (6*6*K) output (C).

Because this is a (6*6*C) and (6*6*C) multiplication, not convolution anymore, why B11 will only interact with A11？

**Comment by oscarriddle** [comment]
Hi @xuqiantong 
In the function kernel_128_winograd_AtIA() from the file Kernel128_winograd.cu.
I noticed below line between the AT and A, which I'm not quite understand.
`  if (Inx > 3 || (Tilex == 3 && Inx > 1)) return;`
Could you provide some intuitive explanations about what do these two conditions represent?

Thanks

**Comment by oscarriddle** [comment]
Hi, @xuqiantong 

I managed to fix the Kernel128_one.cu, now the convolution is getting the correct answer as the same as cuDNN (the BN and ReLU are not included).

However, my kernel is extremely low (>550us) compared to cuDNN (algo 0), which only takes ~100us.
I'm not sure where did the gap come from, would you help take a look at my code?
I only modified the below part of your kernel codes:
```
        // This is your calculation logic
	for (int k = 0; k < 128; k += 16) {
		for (int i = 0; i < 16; i++)
			weights[ind + i*512] = B[(k+i)*512 + ind];
		__syncthreads();

		float *A_start = input + k*64;
		for (int p = 0; p < 64; p++) {
			output[ind] += A_start[line*512 + p] * weights[in_channel + p*128];
		}
		__syncthreads();
	}

	float *C_start = C + tile*512, res = scale[in_channel] * output[ind] + bias[in_channel];
	C_start[ind] = res > 0 ? res : 0;	

```
Here is the full code of my kernel, please refer to my comment to understand the idea.
```
__global__ void kernel_512_one_128(float *A, float *B, float *bnBias, float *bnScale, float *C) {
  int tile = blockIdx.x, in_channel = threadIdx.x, line = threadIdx.y;
  int ind = line*128 + in_channel;
  extern __shared__ float shared_[];
  float *weights = shared_ + 512*4, *output = weights + 128*64, *input = shared_;
  float *bias = output + 4*128, *scale = bias + 128;

  for (int i = 0; i < 4; i++) {
    input[ind + i*512] = A[tile*2048 + i*512 + ind];
  }

  bias[in_channel] = bnBias[in_channel];
  scale[in_channel] = bnScale[in_channel];
  output[ind] = 0.0f;
  __syncthreads();

// The B is transposed and (128*512), every block has dims (y=4, x=128) and generates (4*128)
// output matrix, hence the input is (4*512) and each time weights is (128*64) and with 8 iterations.

  for (int k=0; k<512; k+=64){
    for (int j=0; j<16; j++) {
      weights[in_channel*64+j*4+line] = B[in_channel*512+k+j*4+line];
    } 
    __syncthreads();
    for (int j=0; j<64; j++) {                                                 
      output[ind] += input[line*512+k+j] * weights[j+in_channel*64];
    }
  }
  __syncthreads();
  float *C_start = C + tile*4*128;                                                                                                
  C_start[ind] = output[ind];
}

```

Here is testing log:
```
---- Iter: 9 ----
TotalTime = 550 us
cudaSuccess
cuDNN TotalTime = 95 us
cudaSuccess 
[max_error: 0.000000][error_cnt: 0] 
Average Duration cuDNN: 92 us 
Average Duration Mine: 550 us 
```

It's much appreciated if you would give some advice, my calculation method is based on your idea, but I'm not able to figure out why the calculation takes so long time.
You could just copy my codes on your env and give it a shot.

Thanks.

**Comment by oscarriddle** [comment]
@xuqiantong 
Hi, would you help take a look at my previous comment and give some advice? 
Thanks

**Comment by xuqiantong** [comment]
Hi @oscarriddle, sorry for the late response. I finally get some time this weekend to debug this and your message was very helpful. Actually, I added a `transpose()` for the weights before those cudnn calls, because the column-major is the most friendly order for both my kernels and cudnn's. And indeed, my kernels slowed down after fixing the bugs.

- Can you please take a look at the new commit and see if it makes sense to you? 
- If you have access to TITAN X, can you please update the benchmarks for me in readme? 

Thanks!

**Comment by oscarriddle** [comment]
Hi @xuqiantong , thanks for your reply. 
Since then, I managed to rewrite the one and winograd kernels in a more common and efficient way, because your computation part is too unique and lack of portability. 
For the one kernel, I designed an efficient matrix-multiplication kernel which reached 45us (conv+bn+relu) on TitanXP and the result is correct.

**Comment by xuqiantong** [comment]
That's great! Do you mind share it somewhere?

**Comment by oscarriddle** [comment]
The (1x1) kernel is no more than a 2D matrix multiplication, and an efficiency way of dealing with it is using shared memory with size-fixed tiling. 

The TitanXP provides 40KB shared memory, but I didn't use that much (2\*16\*16<<2 for MM and 4\*6\*6<<2 for transpose). Also there exists overhead but can be avoided by further tricks like unrolling. The WINOGRAD BTdB and ATdA can also follow this idea. You may refer to this repo: [MatrixMultSharedTiledCuda](https://github.com/ozturkosu/MatrixMultSharedTiledCuda)

I think convert most CUDA problems to MM or MM-like problems would be a nice idea, because of good portability and not-that-bad speed. Would like to hear about what do you think.

Thanks to your repo again. It's indeed inspiring and helped me established a deeper vision.
There is still quite a lot work to do :)

------------------
This is the result of my version (3x3) wino kernel, which is general designed with portability.
The speed is slightly slower than your version (56~59us), I think the gap comes from the BTdB kernel. I can make the speed faster by solving potential bank conflict, overhead, etc.
```
---- Iter: 99 ----
TotalTime = 62 us
cudaSuccess
cuDNN TotalTime = 84 us
cudaSuccess
[max_error: 0.000008][error_cnt: 0]
Average Total Time: [Mine: 61 us], [cuDNN: 84 us]
```
